/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Simple data to show the system as working properly */
        get: operations["getAuthInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Simple data to show the system as working properly */
        get: operations["getHealthcheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthcheck/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Simple data to show the system as working properly with authentication */
        get: operations["getHealthcheckAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    json: {
                        github?: {
                            authorizeUri: string;
                            revokeUri: string;
                            tokenUri: string;
                            scopes: string[];
                        };
                        google?: {
                            authorizeUri: string;
                            revokeUri: string;
                            tokenUri: string;
                            scopes: string[];
                        };
                        facebook?: {
                            authorizeUri: string;
                            revokeUri: string;
                            tokenUri: string;
                            scopes: string[];
                        };
                    };
                };
            };
        };
    };
    getHealthcheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    json: {
                        env: string;
                        /** Format: date-time */
                        currentTime: string;
                        uptime: number;
                    };
                };
            };
        };
    };
    getHealthcheckAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    json: {
                        env: string;
                        /** Format: date-time */
                        currentTime: string;
                        uptime: number;
                        userName: string;
                        /** Format: email */
                        userEmail: string;
                    };
                };
            };
        };
    };
}
